Google analytics added
Flux-Tailor/rate-plan-documentation pull request #18
Opened 2024-10-11 21:15 UTC by aminata-cisse-fluxtailor

2024-10-13 19:07 UTC, jonah-bossewitch-fluxtailor requested changes
Hi Aminata - 

Nice work! 🔥 

I left a few inline comments, about venvs w/in the Github action, redundant requirement installs, and different ways to filter out dev traffic.  Probably worth discussing further to see if you have questions, but shouldn't block reworking this PR.

A few other general changes - 

First, we should exclude .DS_Store in .gitignore, like here https://github.com/Flux-Tailor/rate-plan-test-cases/blob/main/.gitignore#L164-L165.   That file a MacOS specific HFS file and should not be commited.  Please add this line to .gitignore and remove these files from the merge.

Next, do you know why the OxygenDocs and input.md files are part of this PR?  Did you add and commit them?  I dont see diffs and am not sure if have a different character for newlines. Did you create your branch directly from main, or from another branch you were working on.  I'm confused why all these files are part of this PR.

Thanks!

2024-10-13 19:07 UTC, jonah-bossewitch-fluxtailor commented on doc/conf.py
> +if os.getenv("GITHUB_ACTIONS"):
Another aside. 

Mature codebases (this is not one yet) often include an easy way to differentiate environments, such as sandbox, dev, stating and prod, often defined in a variable.   We should review this sometime as well https://12factor.net/

2024-10-14 14:57 UTC, aminata-cisse-fluxtailor commented on .github/workflows/build-docs.yml
> +           # We create another virtual environment to isolate our project dependencies
Thank you Jonah, that makes a lot of sense!

2024-10-14 14:57 UTC, aminata-cisse-fluxtailor commented on doc/conf.py
> +if os.getenv("GITHUB_ACTIONS"):
Will do, thanks for sharing

2024-10-14 15:53 UTC, closed without merging