Intro page
Flux-Tailor/rate-plan-documentation pull request #6
Opened 2024-09-19 20:24 UTC by aminata-cisse-fluxtailor

2024-09-19 22:05 UTC, jonah-bossewitch-fluxtailor requested changes
Hi @aminata-cisse-fluxtailor,

Fantastic!  Glad you got this all running smoothly.  🚀 

This PR looks really good to me except for a few small tweaks which I indicated inline.

And, can you please remove the `some-feature.md` and `another-feature.md` pages - those are becoming confusing as we build out the actual contnet.

cheers,
/Jonah

2024-09-19 22:05 UTC, jonah-bossewitch-fluxtailor commented on doc/conf.py
> +html_static_path = ['OxygenDocs']
Hmmm...  Why does this newline keep getting deleted?  Does your IDE keep deleting it?  I'm not certain if we need it or not, but some files may be sensitive.   I saw this https://community.devsense.com/d/1748-formatter-how-to-disable-removal-of-new-line-at-eof/2 and there may be a setting in Visual Studio worth double checking.

Not a big deal if this stays removed, but I wanted to figure out if this was happening automatically.

2024-09-19 22:05 UTC, jonah-bossewitch-fluxtailor commented on doc/index.md
> +:maxdepth: 2
Did we want to try a maxdepth of 3?  I think for our outline that might look better.

2024-09-20 15:20 UTC, aminata-cisse-fluxtailor commented on doc/conf.py
> +html_static_path = ['OxygenDocs']
I just enabled the setting that might help with the default trimming, hopefully that works!

2024-09-23 14:07 UTC, merged